package com.example.kotlindemogithubproject.dao

import org.greenrobot.greendao.annotation.Entity
import org.greenrobot.greendao.annotation.Generated
import org.greenrobot.greendao.annotation.Id
import org.greenrobot.greendao.annotation.NotNull

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LOCAL_USER".
 */
@Entity
class LocalUser {
    @Id
    @NotNull
    @get:NotNull
    var login: String? = null
    var name: String? = null
    var avatarUrl: String? = null
    var followers: Int? = null
    var following: Int? = null

    @Generated
    constructor() {
    }

    constructor(login: String) {
        this.login = login
    }

    @Generated
    constructor(login: String, name: String?, avatarUrl: String?, followers: Int?, following: Int?) {
        this.login = login
        this.name = name
        this.avatarUrl = avatarUrl
        this.followers = followers
        this.following = following
    }

}
